version: "2"
services:

  guacamole:
    image: guacamole/guacamole:latest
    environment:
      GUACAMOLE_HOME: /opt/guacamole/home
      GUACD_HOSTNAME: guacd
      # Don't include this JAVA_OPTS settings in production applications
      JAVA_OPTS: "-Djava.security.egd=file:/dev/./urandom"
    depends_on: 
      - guacd
    volumes:
      - $PWD/config/basic:/opt/guacamole/home:ro

  guacd:
    image: guacamole/guacd:latest

  proxy:
    image: guacamole-demo-proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - guacamole
    volumes:
      - $PWD/proxy/cert:/etc/nginx/cert:ro
