# This stack configuration is the same as proxy.yml except that
# 
# 1. It mounts GUACAMOLE_HOME from config/basic. This will allow us
#    to explore some of the basic features of Guacamole by editing 
#    the user-mapping.xml configuration file.
# 2. It sets a JRE property to reduce the start up time for Guacamole.
#    As noted in the configuration, while this is fine to do for demo,
#    you shouldn't do this in a production configuration.

version: "2"
services:

  guacamole:
    image: guacamole/guacamole:latest
    environment:
      GUACAMOLE_HOME: /opt/guacamole/home
      GUACD_HOSTNAME: guacd
      # Don't include this JAVA_OPTS settings in production applications
      JAVA_OPTS: "-Djava.security.egd=file:/dev/./urandom"
    depends_on: 
      - guacd
    volumes:
      - $PWD/config/basic:/opt/guacamole/home:ro

  guacd:
    image: guacamole/guacd:latest

  proxy:
    image: guacamole-demo-proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - guacamole
    volumes:
      - $PWD/cert:/etc/nginx/cert:ro
