version: "2"

services:
  guacd:
    image: guacamole/guacd:latest

  config:
    image: soulwing/guacamole-demo-config
   
  guacamole:
    image: guacamole/guacamole:latest
    environment:
      GUACAMOLE_HOME: /opt/guacamole/home
      GUACD_HOSTNAME: guacd
    depends_on: 
      - guacd
    volumes_from:
      - config:ro

  proxy:
    image: soulwing/guacamole-demo-proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - guacamole
    volumes:
      - $HOME/guacamole-demo/proxy/cert:/etc/nginix/cert:ro

