# This stack is used for the Minimal Viable Configuration demo
# It uses the configuration in config/minimal, which includes an
# empty user-mapping.xml. It runs the guacamole web server on host
# port 80 and runs guacd on the private network for the stack,
# listening on the default port.

version: "2"
services:
  guacamole:
    image: guacamole/guacamole:latest
    ports:
      - "80:8080"
    environment:
      GUACAMOLE_HOME: /opt/guacamole/home
      GUACD_HOSTNAME: guacd
    depends_on: 
      - guacd
    volumes:
      - $PWD/config/minimal:/opt/guacamole/home:ro

  guacd:
    image: guacamole/guacd:latest
