# This stack configuration extends the minimal.yml to add a nginx-based
# reverse proxy. Note that the certificate used for TLS is mounted into
# the container for the proxy. In this configuration nginx listens on 
# host ports 80 and 443 and it forwards requests to the guacamole container
# over the private network for the stack.

version: "2"
services:

  guacamole:
    image: guacamole/guacamole:latest
    environment:
      GUACAMOLE_HOME: /opt/guacamole/home
      GUACD_HOSTNAME: guacd
    depends_on: 
      - guacd
    volumes:
      - $PWD/config/minimal:/opt/guacamole/home:ro

  guacd:
    image: guacamole/guacd:latest

  proxy:
    image: guacamole-demo-proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - guacamole
    volumes:
      - $PWD/cert:/etc/nginx/cert:ro
