version: "2"
services:
  guacamole:
    image: guacamole/guacamole:latest
    ports:
      - "80:8080"
    environment:
      GUACAMOLE_HOME: /opt/guacamole/home
      GUACD_HOSTNAME: guacd
    depends_on: 
      - guacd
    volumes_from:
      - config:ro

  guacd:
    image: guacamole/guacd:latest

  config:
    image: guacamole-demo-config:minimal
