version: "2"
services:

  guacamole:
    image: guacamole/guacamole:latest
    environment:
      GUACAMOLE_HOME: /opt/guacamole/home
      GUACD_HOSTNAME: guacd
    depends_on: 
      - guacd
    volumes_from:
      - config:ro

  guacd:
    image: guacamole/guacd:latest

  config:
    image: guacamole-demo-config:minimal

  proxy:
    image: guacamole-demo-proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - guacamole
    volumes:
      - $HOME/git/guacamole-demo/proxy/cert:/etc/nginx/cert:ro
